### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by AlexReff** [kickscondor/fraidycat#100]
**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [Git Master branch]

**Describe the bug**
I tried pulling the project locally, but I cannot get it to build. I keep getting this error:

> Error: C:\Projects\fraidycat\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

I tried googling but didn't find anything useful. Are you able to pull on a blank Windows VM and see if you can get it running?

**Steps to Reproduce**

1. Pull Repo
2. `npm install`
3. `npm run electron:setup`
4. `npm run electron:windows`

`npm run electron` also fails for me on Windows.

**Comment by kickscondor** [comment]
I am not going to get to this until next week at least - anyone else able to troubleshoot this?

Thank you for reporting this - it's important to me that everyone can build the software so that they can do what they want with it.

**Comment by johnaoss** [comment]
I seem to be unable to build master on macOS 10.15 Catalina too.

Following these steps:
```
npm install
npm run electron:mac
```

Provides me with the fatal error

```
electron-builder -m                                                                                                                                                                                                                              2581ms  Thu 12 Mar 22:40:37 2020
  • electron-builder  version=22.4.1 os=19.3.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=deasync@0.1.19, fsevents@1.2.11 platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=7.1.14 appOutDir=dist/mac
  ⨯ image: unknown format
github.com/develar/go-fs-util.CloseAndCheckError
	/Volumes/data/go/pkg/mod/github.com/develar/go-fs-util@v0.0.0-20190620175131-69a2d4542206/fs.go:117
github.com/develar/app-builder/pkg/icons.DecodeImageAndClose
	/Volumes/data/Documents/app-builder/pkg/icons/image-util.go:90
github.com/develar/app-builder/pkg/icons.LoadImage
	/Volumes/data/Documents/app-builder/pkg/icons/image-util.go:61
github.com/develar/app-builder/pkg/icons.loadImage
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:334
github.com/develar/app-builder/pkg/icons.configureInputInfoFromSingleFile
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:316
github.com/develar/app-builder/pkg/icons.doConvertIcon
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:241
github.com/develar/app-builder/pkg/icons.ConvertIcon
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
	/Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:90
runtime.main
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373
  ⨯ /usr/local/lib/node_modules/electron-builder/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
```

And then the following for a stack trace:
```
Error: /Users/johnoss/Projects/GitClones/fraidycat/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
at ChildProcess.<anonymous> (/Users/johnoss/Projects/GitClones/fraidycat/node_modules/builder-util/src/util.ts:239:14)
at Object.onceWrapper (events.js:297:20)
at ChildProcess.emit (events.js:209:13)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

Seems like https://github.com/develar/app-builder is being used by `electron-builder`, and may not recognize the image format for whatever reason. I seem to be able to open the built `Electron.app` in `dist/mac`, however a few icons seem to not be missing.

![image](https://user-images.githubusercontent.com/14227035/76585113-f2950f00-64b3-11ea-9559-2f6a5afc00dc.png)

Hacker News seems to have a proper icon, however <https://dataswamp.org/~solene/>'s icon seems to fail to render properly. 

Seems like https://github.com/electron-userland/electron-builder/issues/4134 had the same issue.

**Comment by kickscondor** [comment]
Can you both try running `npm install -D` instead of plain `npm install`?

**Comment by kickscondor** [comment]
Oh you also both need to install git-lfs before cloning. And I need to add that to the instructions!

**Comment by johnaoss** [comment]
Thanks for the info!

Running the following seemed to solve that issue.

```
git clone https://github.com/kickscondor/fraidycat.git
cd fraidycat
git-lfs checkout
npm install -D
npm run electron:mac
```

Although now it seems to fail at the code signing step, but I'll have to dig a little deeper into that one.
