### ISSUE TITLE
Following Instagram profile freezes up the browser, uses 100% CPU

### ISSUE THREAD

**Issue by makeworld-the-better-one** [kickscondor/fraidycat#103]
**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: Fraidycat 1.1.2, Firefox 72.0.2

**Describe the bug**
When trying to add an Instagram profile, the "Following" animation happens repeatedly. Firefox starts using 100% CPU, and although the UI of the browser still works, I cannot load pages anymore, when I try and reload a different tab, it just spins and spins but never finishes. Once I close the browser and reopen it it's okay. But I am still not able to add Instagram. I have content blocking in Standard mode.

**Comment by kickscondor** [comment]
I can't seem to reproduce this. Perhaps it's a specific Instagram account? Can you give me more information? Have you successfully followed other Instagram accounts? Are you able to visit the profile page for the account in another tab?

Thank you for reporting this.

**Comment by makeworld-the-better-one** [comment]
[@example](https://www.instagram.com/example/) and some other accounts I tried worked. The account I'm having an issue with is [@contrapoints](https://www.instagram.com/contrapoints/), I'm not sure why it's the one that doesn't work.

**Comment by kickscondor** [comment]
Ok - I believe I've figured this out. If you restart your browser or turn the extension off and on you should pick up the change.

**Comment by makeworld-the-better-one** [comment]
Restart it how? I've tried something similar. I let the loading animation run for a bit, then closed my browser to fix the freezing. The profile didn't show up after that. Can you explain what you did in more detail?

**Comment by kickscondor** [comment]
Close the browser. Then re-open it. Then, go edit and re-save the contrapoints Instagram follow. This should force a refresh.

It should also fix itself over time - in an hour or in a half-day - depending on what its importance is.

**Comment by makeworld-the-better-one** [comment]
Ok, I disabled and then re-enabled the extension and then it worked, thanks. Any idea why it happened?

**Comment by kickscondor** [comment]
Yep - my Instagram scraper had a bug in it. The specific change is [here](https://github.com/kickscondor/fraidycat/commit/91eb6d4ec3dcb2b323110450138ceed972a63661#diff-09199221ddf064aa666680d4b1f1cd76R226).
