### ISSUE TITLE
Option to hide retweets in Twitter feeds

### ISSUE THREAD

**Issue by nindwen** [kickscondor/fraidycat#104]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**

When I follow people on Twitter with Fraidycat, I'm mostly just interested in seeing what *they* are doing. However, most Twitter feeds are full of retweets of jokes and news, and I don't really care about them. I'd just like to see what they are themselves posting.

For this, I'd like a way to hide the retweets, only showing the original posts by the author. This should probably be some kind of setting, maybe either per-feed, or global? I'd guess not all people would want this, so it probably can't be the default setting, if this even is possible.

**Comment by kickscondor** [comment]
I have this on my todo - someone suggested it in the Hacker News thread. The plan is to add a "Show Reposts" option in the filtering menu on the right. Glad to have this on the list here though so I can track it. Thank you!
