### ISSUE TITLE
Add support for https://are.na/ channels

### ISSUE THREAD

**Issue by tkatchenko** [kickscondor/fraidycat#106]
* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Looks like https://www.are.na/ doesn't support RSS/Atom but it would great to be able to include it. Here are some examples of channels: [https://www.are.na/examples](https://www.are.na/examples).

**Comment by tkatchenko** [comment]
Got an update from are.na, looks like they do support RSS, you have to append "/feed/rss" to the URL although it's not listed in the page head. Not sure if this is something you would want to handle in the app or not though.

**Comment by kickscondor** [comment]
Cool - this is an awesome discovery! Thank you so much for doing the footwork, Thomas!

Yeah so I have adjusted the rules to make this happen. You can restart your browser or turn the extension on and off to enable this change. Works great.
