### ISSUE TITLE
https://news.ycombinator.com/rss is giving a 503 error.

### ISSUE THREAD

**Issue by leliamesteban** [kickscondor/fraidycat#114]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 68
 - URL you are attempting to follow https://news.ycombinator.com/rss

**Describe the bug**

https://news.ycombinator.com/rss is giving a 503 error and fails to import

**Comment by kickscondor** [comment]
I am not able to reproduce this - I tried using Fraidycat 1.1.2 on Firefox 68 for Ubuntu. Can you try subscribing directly to https://news.ycombinator.com/? Do you have any other extensions installed that might be conflicting? It could also have been a hiccup with HN's server.

**Comment by leliamesteban** [comment]
It works now if I use https://news.ycombinator.com/rss. Trying it without /rss still gives the same error.

**Comment by kickscondor** [comment]
This is a rate-limiting thing. It hits the home page and then the RSS feed so quickly, it fires a 503 - I guess I will need to add a delay in.

**Comment by kickscondor** [comment]
I'm now using https://hnrss.org/ behind the scenes to circumvent this issue. If they disappear for any reason, I can swap back. Reload Fraidycat and it should just click.
