### ISSUE TITLE
Enable right-click menu in electron app

### ISSUE THREAD

**Issue by vyaas** [kickscondor/fraidycat#117]
**Before you start.**

* [x ] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**

I know that a lot of current development is focused on the firefox and chrome extensions, but as a user of neither (I use [qutebrowser](https://github.com/qutebrowser/qutebrowser)), I'm posting this issue. 

A right-click menu would enable the user to copy a link in order to share it (which I currently do by opening the link in a browser and copying it from there).

**Comment by kickscondor** [comment]
Good point - there's a right-click menu on input boxes, so the code for this should be similar. Thanks!

**Comment by froztbyte** [comment]
+1 on the feature request for copying link from right-click menu, I was actually just checking the issues now to see if anyone had asked :)

Also willing to test beta release of it if that helps

**Comment by kickscondor** [comment]
Since I'm moving away from Electron in the next few months - this will not be a problem at that time. (Fraidycat will open in a normal browser window instead.)
