### ISSUE TITLE
Fraidycat uses U+2BA8 and U+1F7AB, not rendered in macOS by default

### ISSUE THREAD

**Issue by roversch** [kickscondor/fraidycat#119]
On my Macbook Pro (macOS Sierra 10.12.6), (running Firefox 74.0), there was no font installed that had Unicode characters
 
 - BLACK CURVED DOWNWARDS AND LEFTWARDS ARROW (U+2BA8)
 - BOLD SALTIRE (U+1F7AB)

used in Fraidycat. I had to install a font 'Symbola', after that it rendered correctly.

**Comment by kickscondor** [comment]
Hi, Robin! I believe this is a duplicate of #90, which is being worked on. I appreciate the note about Symbola - might see if I can just package it.

**Comment by roversch** [comment]
You're absolutely right that's it is a duplicate. I tried searching, but I couldn'f find the other issue.

**Comment by kickscondor** [comment]
No trouble at all. Please don't hesitate to open new issues - it's difficult to look through each one. Thank you for the help!
