### ISSUE TITLE
MelonDS RSS feed is empty.

### ISSUE THREAD

**Issue by goaaats** [kickscondor/fraidycat#120]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)
 - URL you are attempting to follow: http://melonds.kuribo64.net/rss.php

**Describe the bug**
When adding this feed URL to fraidycat, the "following" loading screen fails with the error "https://m.facebook.com/$user is giving a 404 error."

![image](https://user-images.githubusercontent.com/16760685/77220915-1f1dea80-6b88-11ea-927c-4413cd044c17.png)

**Comment by j-james** [comment]
Also happens on Firefox 74.0 on Linux for https://www.youtube.com/user/numberphile.

**Comment by kickscondor** [comment]
There is something up with the feed http://melonds.kuribo64.net/rss.php, not sure what yet. But I believe the facebook error should be fixed in the latest release (out tonight or tomorrow). (For reference: this was a problem with some asynchronous calls not being waited for.)

**Comment by kickscondor** [comment]
This ended up being the Content-Type header on the feed. The web server was sending it as text/html. I've fixed this - the release should be out today.
