### ISSUE TITLE
Facebook links no longer update

### ISSUE THREAD

**Issue by grumphus** [kickscondor/fraidycat#126]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version 1.1.3
 - Any Facebook URL

**Describe the bug**
All of my existing Facebook public page links stopped tracking. I tried adding new ones and no posts appear. I understand Facebook support is on the weaker side but I found it working just fine over the past month until just yesterday. Same problem exists on the Windows version. Perhaps it is related to Facebook pages now having "pg" on their URL?

Thank you!

**Comment by kickscondor** [comment]
Ok thank you! Looking into this.

**Comment by kickscondor** [comment]
Ok - yes, sorted this out. A fix will be out tomorrow.
