### ISSUE TITLE
youtube channel wont work

### ISSUE THREAD

**Issue by wanghaisheng** [kickscondor/fraidycat#127]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: [ Mac]
 - Browser [Chrome]
 - Version [https://fraidyc.at/s/#!/add]
 - URL you are attempting to follow [if applicable]
https://youtube.com/user/TopTrendingTV
https://www.youtube.com/channel/UCe3MKYHJnM97ndvDdXrmyMA/videos

**Describe the bug**
it tells me 
Couldn't connect - check your spelling, be sure this URL really exists.

**Comment by kickscondor** [comment]
These both work fine for me. Perhaps the HTML is different when connecting from China.

Can you give me a dump?

```
wget "https://youtube.com/user/TopTrendingTV"
wget "https://www.youtube.com/feeds/videos.xml?channel_id=UCe3MKYHJnM97ndvDdXrmyMA"
```

Thank you!

**Comment by wanghaisheng** [comment]
use  chrome+ SwitchyOmega(Vpn)
i dont see terminal result can help, even though


[archive.zip](https://github.com/kickscondor/fraidycat/files/4474953/archive.zip)

**Comment by medicinecal** [comment]
Is this still broken for you? You can try to access the feed here: https://www.youtube.com/feeds/videos.xml?channel_id=UCtg5C-d_3rPUgMaxr285mQQ - does that work for you?
