### ISSUE TITLE
System Tiddlers Should Be Excluded from TiddlyWiki Sources

### ISSUE THREAD

**Issue by manmademagic** [kickscondor/fraidycat#128]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.5.123 (Chromium: 80.0.3987.163)
 - URL: https://wiki.robinson.dev

**Describe the bug**
System Tiddlers are coming through, when they probably shouldn't be.

Tiddlers beginning with `$:/` are hidden from most views inside of TiddlyWiki, as they're generally used for backend stuff. (Plugins/CSS/Favicon/other junk that _**most**_ people wouldn't care about)

These should probably be excluded from the list of entries.
![image](https://user-images.githubusercontent.com/10588836/79330104-83478a80-7f4b-11ea-86f1-50eb12468e2c.png)

**Comment by kickscondor** [comment]
Ok awesome - this turned out be a bug recently introduced. (Had already been weeding this stuff out but it broke.) If you reload Fraidycat, it should pick up the fix. Thank yooo, Daniel!
