### ISSUE TITLE
Headlines not ordered according to the publication date

### ISSUE THREAD

**Issue by Ikemitsu1** [kickscondor/fraidycat#131]
Fraidycat puts headlines in the wrong order. Seems it doesn't look up the actual publication dates of the posts but uses the order of posts as they appear in the feed file. So in some feeds the headlines are in the wrong order and some old posts can appear as newer. I think Fraidycat should look up the posts' publication dates from the file and not rely on the order the posts are listed.

**Comment by kickscondor** [comment]
Can you show me the publication that is out of order? It should be organizing by publication date (newest to oldest) - unless the feed is wrong. But, who knows, there could be a bug here!

Help me out by posting what platform/browser you are using and what site you are trying to follow. Muchas gracias, humble rabbit!

**Comment by Ikemitsu1** [comment]
Here's one feed that shows out of order for me in Fraidycat: https://haveibeenpwned.com/

Initially I noticed the problem with a feed I publish myself and I could check that in the file the items were correctly dated but not in descending order. When I reordered the items, Fraidycat showed the feed correctly.

I have macOS 10.13.6 and Firefox 75.0.

**Comment by Ikemitsu1** [comment]
I'm also seeing that Fraidycat shows a headline although it has been removed from the feed. This is another feed, one of my owns and not connected to the above issue. So the feed is not updating really. Cache behavior?

**Comment by kickscondor** [comment]
> I'm also seeing that Fraidycat shows a headline although it has been removed from the feed. This is another feed, one of my owns and not connected to the above issue. So the feed is not updating really. Cache behavior? Uh, maybe I should have started a new thread for this...

Ok I've added your other issue - definitely needs to be fixed - #134. Haven't been able to reproduce the other issue yet. Is the feed URL this one - https://feeds.feedburner.com/HaveIBeenPwnedLatestBreaches?

**Comment by Ikemitsu1** [comment]
Yes, that's the feed. Feedburner lists the titles in the correct order as does NetNewsWire (my other feed app on Mac) but Fraidycat is not following the publication order. Oddly also the usual "ago" info is missing.

As said, I originally spotted this with my own feed but I'm not able to reproduce it. I moved an older post to the top of the file on purpose and subscribed this newly created disordered feed but Fraidycat shows the feed according to the publication date tags. This was not the case originally. I'm not sure the case with HaveIBeenPawned feed is similar to mine, though. It just behaves similarly.

**Comment by Ikemitsu1** [comment]
I also deleted the HaveIBeenBowned feed to re-subscribe it but the issue persists. The order of the titles changed but they are still in the wrong order and there's no "ago" info.

**Comment by kickscondor** [comment]
Ok - I've figured out the issue with this feed. Fraidycat was having issues with the date format on some browsers. The fix for this should be out in the next few days. My thanks for all of the helpful details you provided!
