### ISSUE TITLE
Desktop window frame not remembered for future sessions

### ISSUE THREAD

**Issue by tmprk** [kickscondor/fraidycat#132]
I adjusted the window to fit my screen but whenever I quit and reopen fraidycat, it seems to always start in the center at a smaller size. I'm on macOS 10.15.4.

**Comment by kickscondor** [comment]
I am going to be moving away from Electron in the next release - so Fraidycat will launch in a normal browser window. But I will leave this open in case the move doesn't work out in a timely fashion.

Thank you for reporting this.
