### ISSUE TITLE
Fraidycat displays `<![CDATA[]]>` (verbatim)

### ISSUE THREAD

**Issue by kseistrup** [kickscondor/fraidycat#133]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Waterfox (Firefox)
 - Version 2020.04
 - URL you are attempting to follow [if applicable]

https://content.tv2bornholm.dk/helpers/rss?type=nyheder

**Describe the bug**

Fraidycat displays `<![CDATA[]]>` in `<title/>` sections when it shouldn't:

![cdata](https://user-images.githubusercontent.com/25586/80513077-d0c9eb80-897e-11ea-9c85-dc0058b3a32b.png)

**Comment by kickscondor** [comment]
Thank you! I haven't had much time for Fraidycat this past week - but this is will be addressed this coming week.

**Comment by kickscondor** [comment]
Ok, I figured this out - this was a bug in Fraidyscrape. Basically, the feed was being parsed as HTML (rather than XML). A fix should be out in the next few days. Apologies for the long wait. Thank you!

**Comment by kseistrup** [comment]
Great, thanks!
