### ISSUE TITLE
Allow custom feed using CSS selectors for pages not having RSS feed

### ISSUE THREAD

**Issue by rootkea** [kickscondor/fraidycat#136]
* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
Hello!

First of all, a big fan of FraidyCat and the IndieWeb! Unfortunately, not all (most) of the Internet provides RSS feed. So for sites like these user can generate custom feed using CSS selectors and follow such sites/pages.

E.g. https://news.ycombinator.com/best doesn't provide RSS feed and so adding it to FraidyCat doesn't work but I can use `.storylink` CSS selector to get the stories generating the custom feed.

This feature will significantly increase the reach of FaridyCat.

Thanks!

**Comment by kickscondor** [comment]
This is actually already a feature - using XPath instead of CSS selectors - see the [defs/social.json](/kickscondor/fraidycat/blob/master/defs/social.json) file in the tree.

But, for Hacker News, you can also use the feeds here: https://edavis.github.io/hnrss/. I am in the process of automatically using these.

**Comment by rootkea** [comment]
> But, for Hacker News, you can also use the feeds here: https://edavis.github.io/hnrss/

Thanks but unfortunately it doesn't provide a feed for https://news.ycombinator.com/best (HN Best list).

> This is actually already a feature - using XPath instead of CSS selectors.

Umm.. So how do I use it? What do I put here in URL box for https://news.ycombinator.com/best ?
![Screenshot from 2020-05-08 15-52-09](https://user-images.githubusercontent.com/2694559/81396985-fb9e0780-9115-11ea-994c-91534b3b5def.png)

**Comment by kickscondor** [comment]
I'm sorry - but I don't think there's enough information on the /best page to scrape it. It doesn't have the actual dates of each post on that page.

I think your best bet for now is to use this feed: https://hnrss.org/newest?points=300.

Perhaps in the future I can look at using this: https://github.com/HackerNews/API.

**Comment by rootkea** [comment]
> I'm sorry - but I don't think there's enough information on the /best page to scrape it.

How about the `.storylink` CSS selector. It fetches all the stories on the /best page which explains this request for CSS selectors support in FraidyCat.

> It doesn't have the actual dates of each post on that page.

Ah, yes. So maybe FraidyCat can fetch all the 30 stories on /best page using `.storylink` each time? Instead of the usual partial fetching using the date of last fetched data.

Actually, consider this as a general feature and nothing specific to HN best list. If FraidyCat supports CSS selectors then user can fetch any webpage (having proper and definite CSS selectors) even if it doesn't use RSS or the post date. Just specify the selector and the no. of entries to fetch (if not interested in all of the entries on the page) and you are done!

> Perhaps in the future I can look at using this: https://github.com/HackerNews/API.

That will be good too and will work for the specific case of HN best list.

**Comment by kickscondor** [comment]
I'm afraid I'm not interested in adding a CSS selector box to Fraidycat like you want. I don't believe that anyone will use it - and I will have to maintain it. I feel like I've given you some good options here.

And please don't be disheartened - I appreciate the suggestions, Avinash!

**Comment by rootkea** [comment]
It's okay. :)

Thank you for the recommendations though!
