### ISSUE TITLE
Dropdown icon missing

### ISSUE THREAD

**Issue by natestemen** [kickscondor/fraidycat#137]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox
 - Version 75

**Describe the bug**
Best described with pictures. First, in the default view:
![Screen Shot 2020-05-07 at 3 18 57 PM](https://user-images.githubusercontent.com/12703123/81336014-88918400-9076-11ea-87e8-9c638c473416.png)
After clicking the dropdown:
![Screen Shot 2020-05-07 at 3 19 05 PM](https://user-images.githubusercontent.com/12703123/81336013-87f8ed80-9076-11ea-87ce-0818542e37da.png)

From here it looks like the down triangle is missing.

Very much enjoying Fraidycat though, thanks for making it!

**Comment by kickscondor** [comment]
Cool. Thank you for this, Nate! Moving the conversation to #90. I will get this fixed soon.
