### ISSUE TITLE
Show subscribers or the count of them

### ISSUE THREAD

**Issue by httpsterio** [kickscondor/fraidycat#145]
* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
This might be related to #6, I was thinking as a domain owner I'd like to know who is subscribed to my feed and if possible, follow them back. Could Fraidycat when requested for an/my url, return who is subscribed if they've marked it public OR at least get a count of how many is following my feeds?

**Comment by kickscondor** [comment]
You will get one request per person - there is no central server. So every individual browser and computer will access your feed - you can refer to your server logs for numbers.

And I'm afraid even I don't know *who* is using Fraidycat. (This is part of the 'fraidy' part - in that I leave people alone.) So I am unable to send usernames or anything.

If I end up having feed sharing, you should be able to search for your feed and see who is sharing it. So yes - I think this is best attached to #6. 

Thanks Sami! Glad you asked.
