### ISSUE TITLE
Consolidate several feeds into one item

### ISSUE THREAD

**Issue by httpsterio** [kickscondor/fraidycat#146]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
If this is requested already, I'm sorry as I tried to look for it.

Users I follow use several platforms like Twitter, HN, Soundcloud etc. I would like to add all of those feeds under that single individual person and see all of their updates no matter the platform, under that person.

**Comment by kickscondor** [comment]
Oh hey - hi Sami!

Yes this is already an item in progress - #21. Definitely an important one - I agree! Thank you for chiming in.

**Comment by httpsterio** [comment]
OK awesome, thanks :)
