### ISSUE TITLE
Feature request: Scrollable tab bar

### ISSUE THREAD

**Issue by hughwilliams94** [kickscondor/fraidycat#147]
Using the extension on Firefox Mobile works exceptionally well for me apart from one small point, navigating between tabs is slow. Is there some way to make the tab bar scrollable on mobile? I mean so that it can be navigated by swiping left/right rather than using the existing left/right arrow buttons.

**Comment by hughwilliams94** [comment]
Made a quick PR (#148) , not ever really done any web development stuff, but I just tinkered in the dev tools until it kind of worked and then tried to find the appropriate place in the fraidy.scss file.

**Comment by kickscondor** [comment]
Ok - in my testing, this works well enough and should be out in 1.1.6 on Monday.

In the next few months I will be redoing the tabs anyway, so this will at least make things a bit more tolerable until then.

Thank you so much, Hugh!
