### ISSUE TITLE
Support Atom feed tokens?

### ISSUE THREAD

**Issue by lucible** [kickscondor/fraidycat#15]
Would it be possible to support an atom feed with a token at the end of it? For example, `https://webmention.io/api/mentions.atom?token=...`

I'm not really familiar with how atom feeds work and I haven't looked at Fraidycat's code, so I don't know how realistic this request is! :open_mouth: No worries if it's out of scope at the moment, of course.

**Comment by kickscondor** [comment]
Oh, wow - didn't realize these feeds were available.

So, yes - just tested, works fine. Great stuff.

**Comment by kickscondor** [comment]
Oh, nvm - this is broken. This is the thing fluffy has been talking about - the feed refers back to itself without the token.

Ok, sweet - good find!

**Comment by kickscondor** [comment]
Well, nvm - this has been working for me. The link you click for the title goes nowhere - but that's a problem with the feed it seems.

**Comment by lucible** [comment]
aha! yes, working on my end! very awesome. :grinning:
