### ISSUE TITLE
RSS entry summaries

### ISSUE THREAD

**Issue by hughwilliams94** [kickscondor/fraidycat#150]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
Any chance that we can see the summary attached to RSS entries within Fraidycat? For instance when using the Hacker News RSS feeds from hnrss.org (e.g. https://hnrss.org/frontpage), the links to the Hacker New comments sections are also included in the description and it would be great to be able to access them.

**Comment by adilosa** [comment]
Probably releated to #93

**Comment by kickscondor** [comment]
Yes, thank you, Andrew. And actually #30 will cover this. This is absolutely important to me as well.
