### ISSUE TITLE
Ability to follow Steam Game Announcements

### ISSUE THREAD

**Issue by manmademagic** [kickscondor/fraidycat#157]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**

Most games on Steam have an announcements section where details about updates/patches gets posted.
This needs to be viewed individually per game, which makes it a bit of a nightmare when you're a game hoarder that's paid for one too many Humble Bundles.

I think this would be very useful for Early Access games that are still getting frequent updates. Maybe even more useful for those games you haven't touched in years that drop a massive update out of the blue.

---
Steam has a publicly available API to get this news info:
https://developer.valvesoftware.com/wiki/Steam_Web_API#GetNewsForApp_.28v0002.29

It mostly just requires passing through the _**APPID**_ of the game through to the following url:
<pre>
http://api.steampowered.com/ISteamNews/GetNewsForApp/v0002/?appid=<b><i>APPID</i></b>&count=10&maxlength=1&format=json
</pre>
_**count** set to 10 to be inline with Fraidycat and **maxlength** set to 1 because we don't care about the text_

---
Using the game Noita as an example:

Steam Store Page: https://store.steampowered.com/app/881100/Noita/
Announcement Page: https://steamcommunity.com/app/881100/announcements/
Announcement API Page: http://api.steampowered.com/ISteamNews/GetNewsForApp/v0002/?appid=881100&count=10&maxlength=1&format=json

Snippet response from the API:
```javascript
{
  "appnews": {
    "appid": 881100,
    "newsitems": [
      {
        "gid": "3112496281287942512",
        "title": "HOTFIXES - May 20 2020",
        "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/3112496281287942512",
        "is_external_url": true,
        "author": "Nolla Games",
        "contents": "H...",
        "feedlabel": "Community Announcements",
        "date": 1589985233,
        "feedname": "steam_community_announcements",
        "feed_type": 1,
        "appid": 881100,
        "tags": [
          "patchnotes"
        ]
      },
      {
        "gid": "3127131079133130863",
        "title": "Noita's Feast update chows down on some deadly new spells",
        "url": "https://steamstore-a.akamaihd.net/news/externalpost/rps/3127131079133130863",
        "is_external_url": true,
        "author": "contact@rockpapershotgun.com (Natalie Clayton)",
        "contents": "<a href=\"https://assets.rockpapershotgun.com/images/2020/02/noita-deer.png\"> ...</a>",
        "feedlabel": "Rock, Paper, Shotgun",
        "date": 1588438459,
        "feedname": "rps",
        "feed_type": 0,
        "appid": 881100
      },
      /* TRUNCATED TO NOT BLOAT THIS REQUEST TOO MUCH */
    ],
    "count": 49
  }
}
```

So for these it would just be checking `appnews.newsitems[i].url` and `appnews.newsitems[i].title`.
It may also be worth filtering based on the `appnews.newsitems[i].feedname`, as by default the API pulls in syndicated news stories. Limiting to just _**steam_community_announcements**_ would keep it as official announcements only.

**Comment by kickscondor** [comment]
Cool - I like this! I've had to delay 1.1.6 because of a bug - so I'm going to wrap this up into that. Thankyou, Daniel.

**Comment by medicinecal** [comment]
OK this was pretty easy! Thank you to your instructions this is done.
