### ISSUE TITLE
Following Twitter Feed Complains About 429 Error

### ISSUE THREAD

**Issue by mitchellgordon95** [kickscondor/fraidycat#159]
**Before you start.**

* [X] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [X] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version (Chrome) 83.0.4103.106  (FraidyCat) 1.1.5
 - URL you are attempting to follow : https://twitter.com/sleepinyourhat

**Describe the bug**

Upon attempting to follow the above Twitter URL, an alert box shows up saying that the URL is returning a 429 error. Screenshots attached. (Sorry, I couldn't copy the error text for some reason.)
![image](https://user-images.githubusercontent.com/7490438/85622610-1a5c4d00-b635-11ea-84a2-68c8f32e4601.png)
![image](https://user-images.githubusercontent.com/7490438/85622622-1e886a80-b635-11ea-86d4-a2b9adcf8680.png)

Let me know if you need any more diagnostics. Also, do you have a Patreon / Github sponsors?

**Comment by spacecowb0y** [comment]
I'm experiencing the same issue since the last few weeks. Without digging to deep into the issue, it looks like you should change the scrapping twitter strategy to not hit the rate limit the first time you load the app when you follow X amount of twitter accounts.

**Comment by kickscondor** [comment]
Ok, thank you Mitchell and Diego. I began using the profile.json in the hopes that the rate limit wouldn't be an issue - since it is used for the frontend. However, it looks like I'll need to tune this.

**Comment by kickscondor** [comment]
Give me an idea - how many follows do you two have?

**Comment by FBemf** [comment]
I'm getting this issue when I try to subscribe to a twitter feed, and I am currently not subscribed to *any* other twitter feeds. So I don't think it could be client-side rate limiting.

```
https://api.twitter.com/2/timeline/profile/14873854.json?include_profile_interstitial_type=0&include_blocking=0&include_blocked_by=0&include_followed_by=1&include_want_retweets=0&include_mute_edge=0&include_can_dm=0&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=false&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&include_tweet_replies=false&userId=14873854&count=40&ext=mediaStats%2ChighlightedLabel%2CcameraMoment&include_quote_count=true is giving a 429 error.
```

**Comment by kickscondor** [comment]
Okay okay! I think I've fixed this. There's no need to upgrade - the change should reach you in the next hour. If you want to force an update, you can open and close your browser - or turn the Fraidycat extension on and off.

Thank you to all of you for reporting this. And, of course, to the Nitter team for [solving this](https://github.com/zedeus/nitter/issues/200) on their project. I just followed their same fix.

**Comment by spacecowb0y** [comment]
Works like a charm, thank you man!

**Comment by FBemf** [comment]
Resolved for me too!
