### ISSUE TITLE
filter by content

### ISSUE THREAD

**Issue by racuna** [kickscondor/fraidycat#160]
I'm following a seismic events on a twitter account, but they post too much data that is not useful to me. I will like to filter them by region using some text pattern, if that is possible to implement in fradiycat.

thank you very much

**Comment by kickscondor** [comment]
Yes - this is planned - see #101. (The main discussion is in #69 tho.)

Unfortunately this is delayed for the Fraidycat 2 rewrite.

**Comment by racuna** [comment]
I'm ok with that :) thank you for you great work

**Comment by kickscondor** [comment]
Cool thanks, racuna.
