### ISSUE TITLE
Allow adding links currently giving 500 or 50x http error code

### ISSUE THREAD

**Issue by coezbek** [kickscondor/fraidycat#162]
**Before you start.**

* [X] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
Dear Kicks,
I love Fraidycat and would think it would be even more awesome if it could accept URLs which do not currently work.

This would be awesome becomes sometimes when adding links, the servers are down/broken *temporarily* and Fraidycat will not accept links at that time.

I would suggest that you allow adding URLs even if they cause an error and/or don't provide valid RSS when adding. Once the service comes back up then Fraidycat can do its work.

Thank youuuu!

**Comment by medicinecal** [comment]
Ok - the error will still be shown - but it will ask "Are you sure you want to add?"
