### ISSUE TITLE
Defaulting to explicit RSS link over social.json rules

### ISSUE THREAD

**Issue by anabh4569** [kickscondor/fraidycat#164]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
Currently, when adding a feed from reddit, Fraidycat is defaulting to the rules in social.json even when providing an explicit RSS link.

For example, when I try to add [https://www.reddit.com/user/buttpoems/submitted/.rss?sort=new](https://www.reddit.com/user/buttpoems/submitted/.rss?sort=new) (to get this guy's posts without comments and sorted by new), it treats the link as if I'm adding [https://www.reddit.com/user/buttpoems](https://www.reddit.com/user/buttpoems), which defaults to overview (including both posts and comments, sorted by top).

**My suggestion is to, if given an explicit RSS link, default to that RSS link without creating a feed link from the social.json rules.**

Note: this happens with subreddits too. Not sure if it happens with other websites. 

My current version is 1.1.5

**Comment by medicinecal** [comment]
Yes. I see the problem. I will try my hand at resolving it tomorrow.
