### ISSUE TITLE
Ability to follow twtxt micro blogs

### ISSUE THREAD

**Issue by eli-oat** [kickscondor/fraidycat#167]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
I'd love the ability to follow [twtxt feeds](https://github.com/buckket/twtxt) through Fraidycat.

**Comment by medicinecal** [comment]
Okay yes. I can try this.

**Comment by medicinecal** [comment]
This has been finished. It should be out by Monday.
