### ISSUE TITLE
format for deviantart follows

### ISSUE THREAD

**Issue by digitalap3** [kickscondor/fraidycat#168]
**Before you start.**

* [X ] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**

Not sure if this is something you can/want to incorporate but to automate a follow for deviantart gallery page the rss is

https://backend.deviantart.com/rss.xml?q=gallery%3A[username] that can be extracted from https://www.deviantart.com/[username]/gallery

really great work I am enjoying this.

**Comment by medicinecal** [comment]
Okay I think I got this working! Thanks to your very clear and perfect description. It should begin to work in your Fraidycat in the next hour.
