### ISSUE TITLE
Cannot find some YouTube RSS feeds

### ISSUE THREAD

**Issue by ryanlukkreung** [kickscondor/fraidycat#170]
**Before you start.**

* [X] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [X] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 1.11.104
 - URL:
https://www.youtube.com/user/canadianwargod
https://www.youtube.com/user/aragusea
etc.

**Describe the bug**
When trying to follow these and other channels in FraidyCat, I get the following pop-up notification from my browser: "fraidyc.at says Cannot find an RSS feed or social media account to follow at this URL."

My best guess is that some channels have a /user link as the default for the channel, which may not be recognizable to FraidyCat.

**Comment by medicinecal** [comment]
Ok restart your browser and give it another go. Thanks for catching this!

**Comment by ryanlukkreung** [comment]
Perfect! Thanks for the quick fix and the fantastic service.
