### ISSUE TITLE
Only top links on reddit can be subscribed

### ISSUE THREAD

**Issue by linsui** [kickscondor/fraidycat#177]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 1.1.6
 - URL you are attempting to follow https://www.reddit.com/r/firefox/new.rss

**Describe the bug**
fraidycat can subscribe top links automatically when a sub reddit url is provided. However, when a explicit new.rss or /new/ url is provided, fraidcat should subscribe newest submissions instead.

**Comment by medicinecal** [comment]
Okay awesome! I did some work on this in #164. But it didn't go far enough. If you reload your extension (or the whole browser), you should pick up the change. Otherwise you'll get the change in about an hour.

Thanks, linsui!
