### ISSUE TITLE
Add UI indicator to show (roughly) when "Tag" or "Importance" categories have been last updated.

### ISSUE THREAD

**Issue by joshuacwnewton** [kickscondor/fraidycat#18]
RSS readers work as a "single page hub" because they allow you to get an overview of all new updates (across various categories) through the use of unread counts. Fraidycat removes unread counts but doesn't seem to replace them with any other UI indicator. 

If you have dozens of tags and importance categories, you must manually click through and check each one. That defeats the purpose of RSS! :P

EDIT: But to be clear, I absolutely love what you're doing and the goals you have! And I think your creations are neat! It just doesn't fit my usage if I have to fall into the same repeated checking habits.

**Comment by kickscondor** [comment]
Well, I feel you - and I know other RSS readers take this approach - and e-mail, apps, etc - but I am uncertain that I will take it. But Fraidycat isn't a 'reader' - and I really don't want Fraidycat to turn into another 'inbox'.

Fraidycat currently has no way to read posts. It is simply not a post-centric reader. (The whole reason for this is to avoid getting in the mindset of feeling an obligation to read every post. When following hundreds of people, it just becomes unmanageable.) So - how do I track if someone has 'read' a post? When they've clicked that post's link? When they've clicked the blog's link? When they've expanded the title list? Do I include a "mark all read" action?

I also dislike notifications. You should command the tool - it should command (or disrupt) you.

I just see it as more of a personal surveillance tool - you can see a view of everything that's out there, but you don't have to dig through it all.

But yeah - if someone had a *really* good idea for subtly incorporating post reading, I would consider it. I apologize if the tool isn't for you and I'm glad if you want to continue to make your case, Joshua - it's interesting to hear how others read the Web and hunt for things.

**Comment by joshuacwnewton** [comment]
Ah, sorry, I may not have been the most clear. I wasn't expecting it to be a reader per se (in that you would want to track every individual item, and whether it's read or not read). I like the shift in mindset that you describe, and it's why I wanted to use Fraidycat in the first place!

The subtle UI element I was picturing was say, a red dot on a tab to indicate "This tab has had new activity since you last clicked on it." Basically just an on/off flag (on when something new happens, off when you click the tab). It wouldn't track the individual posts or anything.

Also, I'm sorry for writing my issue in a way that made you feel the need to apologize. I shouldn't have come across like I was entitled for you to adapt the tool to my needs -- this was borne out of your own usage, not mine! I hope you don't feel any obligation or anything.

**Comment by joshuacwnewton** [comment]
Just to clarify:

>Follows are show in dark green if they have been updated in the past two days, a plain cyan if they are up to a month old and in an unassuming light brown if they are over a month old. A small graph of activity over the past year is displayed - in pink (if showing the previous two months of activity) or in gray (if showing the past six months.)

I like this kind of information, just on the tab level (rather than the source level). Even coloring the tabs with green/cyan would satisfy what I'm hinting at.

**Comment by kickscondor** [comment]
Oh ok - I see, I see. Yeah, I could see this being useful. I'm not sure how to change the interface - I don't like the idea of having more colors and dots everywhere - but perhaps there is a way to do it subtly - maybe even just shading certain tabs subtly.

If I do this, I think I will only have it apply to 'real-time' stuff - I really don't want to notify anyone that the 'yearly' stuff is updated - the whole point is to put those way off on the backburner so that they don't grab your attention.

At any rate, I'm sorry I didn't grasp your concept at first. Now that I look back, I feel that you were quite clear about it. It was the use of 'unread count' that I jumped on.

Anyway - I'm going to reopen this so I can continue thinking about this suggestion.

**Comment by joshuacwnewton** [comment]
Sorry for closing it! I felt a bit self-conscious for intruding on your space and didn't want to impose. I'm glad to hear we're on the same page.

**Comment by kickscondor** [comment]
Addressed - for a start - in the 1.0.4 release. May reopen later - this isn't an exact science.

**Comment by joshuacwnewton** [comment]
Hi @kickscondor! Just wanted to let you know that A) I still use Fraidycat (and love it), and B) I just noticed the tab indicators! 

My initial reaction is that you've done a wonderful job with your implementation! It's so subtle and pretty, and doesn't add clutter to the UI. 

Is there anything I can do to provide useful feedback on the new feature? 

(Also, thank you again for taking the time to respond to my idea and see it through. You had no obligation to but you did it anyway, so I'm very grateful that you'd devote the time. Thanks!!)

**Comment by kickscondor** [comment]
Hey - nice to hear from you again! I'm glad you took the time to explain to me what you meant - I think it's turned out well so far. Although I wouldn't be surprised if, after another month, we have some ideas for improving it. So please drop a comment here if anything occurs to you.
