### ISSUE TITLE
solipsys feed's dates not being parsed correctly

### ISSUE THREAD

**Issue by anabh4569** [kickscondor/fraidycat#180]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 1.1.7
 - URL you are attempting to follow: https://www.solipsys.co.uk/rss.xml

**Describe the bug**
The dates of the entries in this RSS feed aren't being parsed correctly. It's causing the most recent entries not to show up when they're posted.

**Comment by medicinecal** [comment]
There are no dates for those entries in the RSS. (No pubDate entry - or any other dates - on those items.) So Fraidycat is using the current time as the publication date. I would let the site owner know that their feed is broken - as this will probably hinder their readers.

**Comment by anabh4569** [comment]
Got the site owner to fix the feed.
