### ISSUE TITLE
Add "Mark/Unmark as Read" option

### ISSUE THREAD

**Issue by evertonstz** [kickscondor/fraidycat#19]
For feeds that have too much information, like a twitter feed for example, adding a tool to mark something as read would be helpfull. I think a good way to implementing it would be doing something like the "tasks" apps do with their task lists, like google keep. I've made a quick mockup to explain it better, the image can be found here: https://imgur.com/ZyvoGk8

**Comment by kickscondor** [comment]
I've put some similar thoughts in #18 - but basically, I currently feel that reading posts is not something I will bring to Fraidycat. I know this is a huge departure from other RSS readers - but if you are using it to track hundreds (hopefully thousands, eventually) of websites, there's just no possible way to manage the landslide of 'unread' messages.

You just drop into Fraidycat and read whatever you feel like reading. That's the whole vibe. No notifications, no 'you have X unread messages.' (I'm sorry!)

**Comment by evertonstz** [comment]
Tbh it makes sense. I think a good way to avoid having too many posts would be to add an option to "only get posts from past hour/day/week/month" for each source.

**Comment by kickscondor** [comment]
Mmm, yes - that's definitely a possibility. I'm honestly not sure what to do with blogs that have a very high posting frequency. For now, I like just showing the last ten posts and at least having an idea of roughly what that person is talking about right now, without needing to read everything. But there is probably a lot of room for a more sophisticated view there.

Hey, thanks Everton for caring enough to comment and offer ideas!

**Comment by evertonstz** [comment]
No problems bro, we are all in the same fight against attention-predatory websites.

**Comment by kickscondor** [comment]
I believe this is now part of #30. So we'll continue conversation there. Please reopen if you feel differently, of course.
