### ISSUE TITLE
Tumblr feed pulls whole post

### ISSUE THREAD

**Issue by sogen** [kickscondor/fraidycat#190]
**Before you start.**
* [X] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [X] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 1.1.7
 - URL you are attempting to follow: http://mrgan.tumblr.com

**Describe the bug**
Instead of showing only the title, displays whole posts

**Comment by kickscondor** [comment]
Okay I have rolled out improved Tumblr support - titles only, reblogs shows the original author's name, and reply posts get rolled up into a single post - like is done with Twitter. (You can also 'hide reposts' in Fraidycat if you want.)

Thank you for bringing this up! I follow some Tumblrs and have really been wanting to improve the readability.

No need to download anything - should auto-update.
