### ISSUE TITLE
FraidyCat appears to send a second request (minus cookie) to an app in development on localhost:3000

### ISSUE THREAD

**Issue by matthewbloch** [kickscondor/fraidycat#194]
**Before you start.**
* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 83.0
 - URL you are attempting to follow [if applicable]

**Describe the bug**

While developing an app on localhost:3000, I saw double fetches of any page from the app itself while FraidyCat was enabled.

If I fetched e.g. / it would fetch / as normal, then any linked resources (css & images), then finally a second fetch of / without the cookie.

This worked on any URL, e.g. if I fetched /test (which was a 404) my app would log a GET to /test again, the second time without any cookie.

The Network panel in firefox didn't log this second fetch, and the only way I could find to stop it was to disabled FraidyCat.

I suspect this is somehow intended behaviour, but I couldn't work out what set of options might cause it, and the mysterious server log & session spam was confusing until I stopped to track it down.

I've not _proved_ that the second fetch came from Firefox, but it did have Firefox's UA, and I couldn't trigger it with curl or a vanilla Edge install or anything else. So I suppose I'm ruling out my noddy node.js/express app processing requests twice.

**Comment by kickscondor** [comment]
Yes - this is Fraidycat. It attempts to detect follows on the pages visit. Sometimes this requires a fetch.

This will go away in the next release. Sorry about this change!

**Comment by frioux** [comment]
I believe that this either wasn't fixed or has regressed.  I have the same issue but the main difference is the Accept header changes from the normal accept header to just `*/*`.

**Comment by kickscondor** [comment]
This is also being discussed in #178. I have checked in a fix. It should be out soon.

In the meantime, we'll just leave both of these issues open.

**Comment by kickscondor** [comment]
I've submitted a fix for this that is out now for Firefox.

**Comment by frioux** [comment]
looks fixed to me!
