### ISSUE TITLE
YouTube channels show inaccurate update history.

### ISSUE THREAD

**Issue by joshuacwnewton** [kickscondor/fraidycat#20]
When I add a YouTube channel (e.g. https://www.youtube.com/channel/UCZYTClx2T1of7BRZ86-8fow), the recent updates are different than the actual updates.

For comparison, I have also added the invidio.us version of the same channel (https://invidio.us/channel/UCZYTClx2T1of7BRZ86-8fow) which shows the correct update history. 

![history-comparison](https://user-images.githubusercontent.com/16181459/68509804-b06a7100-0226-11ea-92b3-9891a1c1e433.png)

I've copied the urls exactly as shown in their respective fraidycat entries, but if there's any more information I can add to aid in reproducing this, let me know! 

(Also, as a side note, I feel like you might be the kind of person who appreciates invidio.us/nitter as youtube/twitter alternatives. This extension might also be up your alley: https://addons.mozilla.org/en-CA/firefox/addon/invidition/)

**Comment by kickscondor** [comment]
This can happen for a lot of reasons - the main one being that edits to last shows can hit the 'update' time on the entry. Also: live shows that get scheduled will show up before they appear, even if they aren't listed on the 'videos' page.

However, I think I agree with you that Invidious probably has it right. I've been trying the raw feed for the past month, but it just feels confusing, so I'll probably have to just ignore updated videos.

Thanks for everything you're doing, Josh!

**Comment by joshuacwnewton** [comment]
Oh! Thank you for clarifying. You've helped me learn more about Youtube. I didn't realize that edits/live shows had that effect.

Happy to contribute. I support your goals and am glad to see people experimenting in this space. Are.na, Mastodon, Tildes, etc. You name it! Experimentation with web browsing is my jam and I like hearing/sharing ideas.

**Comment by kickscondor** [comment]
Fixed with the 1.0.4 release.
