### ISSUE TITLE
Which rss parser is fraidycat is using?

### ISSUE THREAD

**Issue by tcgumus** [kickscondor/fraidycat#204]
Hello kicks,
Which rss parser you are using in this project?
I couldn't understand. Are you using node-fetch or fraidyscrape to fetch and parse rss feed? 
Thank you.

**Comment by tcgumus** [comment]
I'm lost. 😁 I now think you are using feedme.js . https://github.com/kickscondor/fraidycat/blob/v1.0/src/js/feedycat.js

**Comment by kickscondor** [comment]
Don't know how I missed this question - using Fraidyscrape. (https://github.com/kickscondor/fraidyscrape)
