### ISSUE TITLE
Fraidycat causes Firefox to request every URL twice (when typed in the address bar, outside of the extension)

### ISSUE THREAD

**Issue by coaxial** [kickscondor/fraidycat#212]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 86
 - URL you are attempting to follow: any entered in the URL bar

**Describe the bug**
When FraidyCat is enabled as an addon, any URL I enter in the URL bar (in the browser, the one you get with Ctrl-L) is requested twice. The addon just has to be enabled for this to happen, it doesn't have to be open or anything. There is no reason for the second GET request to happen, the browser should only fetch the requested URL once.

# Repro:

- start a webserver with `python3 -m http.server` for instance
- disable the FraidyCat addon
- navigate to localhost:8000 in a new tab
- enable the addon
- refresh the page
- see that there are two `GET /` requests in the logs from that request
- disable the FraidyCat addon
- refresh the page
- there is now only one `GET /` request from that refresh
- enable the addon
- refresh the page again
- there are now two `GET /` requests from that refresh

http server logs:
```
$ python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
# Initial load, addon disabled
127.0.0.1 - - [17/Mar/2021 19:56:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Mar/2021 19:56:28] code 404, message File not found
127.0.0.1 - - [17/Mar/2021 19:56:28] "GET /favicon.ico HTTP/1.1" 404 -

# refresh, addon enabled
127.0.0.1 - - [17/Mar/2021 19:56:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Mar/2021 19:56:57] "GET / HTTP/1.1" 200 -

# refresh, addon disabled
127.0.0.1 - - [17/Mar/2021 19:57:13] "GET / HTTP/1.1" 200 -

# refresh, addon enabled
127.0.0.1 - - [17/Mar/2021 20:00:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Mar/2021 20:00:13] "GET / HTTP/1.1" 200 -

# refresh, addon disabled
127.0.0.1 - - [17/Mar/2021 20:00:29] "GET / HTTP/1.1" 200 -
```

**Comment by kickscondor** [comment]
Sweet! Thank you for this test case - this is addressed by aabefcd. And is also covered in #178. Hope to have it out very soon.

Sincerest apologies for this bug.

**Comment by coaxial** [comment]
No worries, thanks for your hard work!

**Comment by kickscondor** [comment]
Ok the code that was doing this has been replaced and an update is out now in Firefox. Thanks for holding the line. Let me know how it goes!

**Comment by coaxial** [comment]
Thanks, looks like the fix works for me.
