### ISSUE TITLE
find Neocities feeds

### ISSUE THREAD

**Issue by averageunicorn** [kickscondor/fraidycat#218]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
Neocities is a Geocities-inspired thing for personal websites (many of them weird and 90s-style). Each website has a feed that tells you when it is updated. Nothing more than that, but still cool to let me know when I should go check that site out again because something has changed. It is at `https://neocities.org/site/[sitename].rss`.

That means: when I enter `https://totallymywebsite.neocities.org`, I'd like fraidycat to find `https://neocities.org/site/totallymywebsite.rss`

**Comment by kickscondor** [comment]
Okaaayyy - so I REALLY appreciate this feature request - I follow a bunch of Neocities sites and was unaware of the RSS feed! So thank youuuu, averageunicorn. 🕴️ 

However, the feeds are pretty bad. They only indicate a date of the change - no details on where it occured.

So I think I'm going to work on scraping this page: https://neocities.org/site/unimaginable-heights

**Comment by kickscondor** [comment]
![2021-06-09 18 18 05 fraidyc at 512f3138c313](https://user-images.githubusercontent.com/12375777/121445622-119c7e00-c94f-11eb-8ca8-172354007252.png)

Okay this change has been made - you can restart the extension - or wait an hour - and you should pick it up!

It links to the pages that have changed so you can go to them. Enjoy!
