### ISSUE TITLE
JSON parse error when trying to import any OPML

### ISSUE THREAD

**Issue by Bauke** [kickscondor/fraidycat#22]
Hey, just installed Fraidycat and when I tried to import my OPML I got this error:

```
Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

At first I thought it was the OPML I was trying to import, however it also occurs when I export from Fraidycat and try to import that OPML file.

**Comment by kickscondor** [comment]
Cool - yeah, slight bug in there. Thanks!
