### ISSUE TITLE
"Unable to connect" when opening the fraidycat feed

### ISSUE THREAD

**Issue by aereaux** [kickscondor/fraidycat#221]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 88.0.1

**Describe the bug**
When I click the fraidycat toolbar button to view my feeds, it opens a page (with URL "https://fraidyc.at/s/"), but instead of showing my feeds it displays the Firefox "Unable to connect" page.  When I try curling the URL, it just gives me connection refused.  I am able to view other sites normally.

**Comment by philippnagel** [comment]
Same here:

OS: Ubuntu
Browser: Brave
Version: V1.25.68

Seems like a server-side issue to me.

**Comment by aereaux** [comment]
It looks like it's back up (at least for now).  I'm a little confused why it would require that website to be up, though.  Is it not possible to display the feeds page totally locally?

**Comment by kickscondor** [comment]
Apologies! Had a server upgrade issue I didn't catch.

>  I'm a little confused why it would require that website to be up, though. Is it not possible to display the feeds page totally locally?

I agree! I don't like this situation - here are the details, if you want the full explanation:
https://github.com/kickscondor/fraidycat/wiki/What-Up-With-the-Fraidyc.at-'s'-Page?-Can't-I-Just-View-Feeds-Locally?

**Comment by kickscondor** [comment]
The home for this discussion is #210. Feel free to share further ideas there.

Thank you for taking time to report this!

**Comment by aereaux** [comment]
Thanks for the further info (although the link didn't work for me, looks like the question mark isn't included in the linkified part)

**Comment by kickscondor** [comment]
Oh you're right. https://github.com/kickscondor/fraidycat/wiki/What-Up-With-the-Fraidyc.at-'s'-Page%3F-Can't-I-Just-View-Feeds-Locally%3F
