### ISSUE TITLE
Fraidycat taken down on Chrome Web Store

### ISSUE THREAD

**Issue by TheBlocks** [kickscondor/fraidycat#224]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - URL you are attempting to follow: https://chrome.google.com/webstore/detail/fraidycat/hecfkgekabkkhiidlinmifelhdooeool

**Describe the bug**
Fraidycat is no longer available on the Chrome Web Store. This means that going on https://fraidyc.at/s/ doesn't work anymore. I can only manage to get it running by downloading the 1.1.10 release from the Releases page and manually loading it as a Chrome extension.

**Comment by jmahoney** [comment]
@TheBlocks it's back up now, at least for me.

**Comment by TheBlocks** [comment]
Yep, back up for me too. I'll close my issue.

**Comment by kickscondor** [comment]
Thanks for keeping an eye on this! Just have had to go back and forth with them a bit lately.

**Comment by Liber1917** [comment]
Failed to get the extension again on Chrome Web Store. Manually loading also failed.
