### ISSUE TITLE
Add OPML Subscriptions

### ISSUE THREAD

**Issue by mrkrndvs** [kickscondor/fraidycat#23]
I wonder about the possibility of adding feeds via an OPML file, rather than links one at a time. This is what I like about Inoreader.

**Comment by Bauke** [comment]
This is already possible. #16 

If you click the settings cog in the top right you will see a place to export and import OPML files.

**Comment by mrkrndvs** [comment]
Apologies, I must have overlooked the import button.

Thank you.

Aaron
---

Read Write Respond <http://tinyletter.com/readwriterespond/>

**Comment by kickscondor** [comment]
Hey, thank you, Bauke!
