### ISSUE TITLE
Blank window in Mac OS 1.1.2

### ISSUE THREAD

**Issue by timiscoding** [kickscondor/fraidycat#231]
**Before you start.**

* [X] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [X] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: None, desktop app
 - Version 1.1.2

**Describe the bug**
Get a blank screen on app startup. Thought it might be server related so I waited another day but same. Same as #79
I know there's more up-to-date versions avail but is there anything I can do to save my settings before I'm forced to start over with a fresh install?

[FraidyCat/FIle Storage/Sync/follows.json](https://github.com/kickscondor/fraidycat/files/7318424/follows.txt)
- renamed to `.txt` because github doesn't allow attaching `.json`
- there was also `FraidyCat/File Storage/follows.json` but it was a zero byte file

**Comment by timiscoding** [comment]
Found a fix. I had 2 json files `Users/<name>/Library/ApplicationSupport/Fraidycat/File Storage/follows.json` and `.../File Storage/sync/follows.json`. The first was empty but the second had some data so I attempted a full json import with it and it worked.

**Comment by kickscondor** [comment]
@timiscoding Glad that worked! Apologies that I missed this issue - have been preparing for Fraidycat 2, which has just started going out to testers. Hope it will improve your experience - thanks for sticking with me.
