### ISSUE TITLE
Twitter feeds stopped updating 3 days ago...

### ISSUE THREAD

**Issue by newterritories** [kickscondor/fraidycat#239]
**Before you start.**

* [ X] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [X ] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Version 97.0.4692.99 

**Describe the bug**
For the various Twitter-accounts I follow on Fraidycat, all of them have stopped updating as of 3 days ago. I have reloaded the page several times, and still same. I've checked and all these users have tweeted more recently than 3 days ago. 
Other feeds like from blogs or Reddit are up-to-date and working fine. 
Please help?

**Comment by k0nr** [comment]
Same issue here. 

- OS: Kubuntu 20.04 
- Browser: Firefox
- Version: 96.0

Twitter display names and posts are not updating.

**Comment by hoopyeah** [comment]
Same issue here. 

- OS: Windows 10
- Browser: Firefox
- Version: Nightly
I also get this error in a little pop-up window when adding a new Twitter follow: 
```
JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

Add this follow anyway? (In case it might be down for the moment.)
```

**Comment by omentic** [comment]
Same issue here. Many Nitter instances also broke at about the same time.

**Comment by tomr-stargazer** [comment]
Same here!

**Comment by AaronHofer** [comment]
All her 9 lives are dead, Jim.

**Comment by fasiha** [comment]
> `JSON.parse: unexpected end of data at line 1 column 1 of the JSON data Add this follow anyway? (In case it might be down for the moment.)`

I see this error is generated here: https://github.com/kickscondor/fraidycat/blob/a0d38b0eef5eb3a6a463f58d17e76b02b0aea310/src/js/follows.js#L59-L61

And I see that `error` operation happens here: https://github.com/kickscondor/fraidyscrape/blob/1f447b12b3ef02eb2843211cc207347b44d0ad63/webext/content-script.js#L14-L19

But at least in Firefox I can't seem to find any trace of what fraidyscrape is doing in the Network tab or the Debugger window 😭 any tips on how to debug what's happening? Is there some Firefox extension-specific tool I should be using to gain observability? Thanks for any tips!

**Comment by prettyv** [comment]
> Is there some Firefox extension-specific tool I should be using to gain observability?

You can observe the network activity of extensions via `about:debugging`, select "This Firefox" and find Fraidycat in the extensions list where you can `Inspect` and debug it.

Looks like Twitter is returning HTTP 429 rate limit error responses on the profile timeline GET requests, even though the `X-Rate-Limit-Limit` and `X-Rate-Limit-Remaining` response headers would indicate that they haven't been exceeded.
There was an API update announced around approximately the date updates stopped working (see `https://developer.twitter.com/en/updates/changelog`) even though the listed changes seem unrelated. Maybe something to do with the bearer token? I'm also wondering about the call to `https://api.twitter.com/1.1/guest/activate.json` to get a `guest_token` before each call which is an undocumented endpoint that was only intended for Fabric, which has folded into Firebase quite a while ago in 2020.

**Comment by badgersaurus** [comment]
Just want to say I've been having the same issue on the standalone desktop version, except for longer; about 20 days now I think.
OS: Windows 10
Version: 1.1.7

**Comment by rgieseke** [comment]
As a workaround one can export the full JSON file and then replace all occurrences of "twitter.com" with "nitter.net".
After re-importing the changed `fraidycat.json` it will use Nitter's RSS feeds.
The old Twitter feeds are (brokenly) still there (and getting requests) so I somehow managed to completely clear Fraidycat's internal storage with `browser.storage.sync.clear()` and/or `browser.storage.local.clear()` in the console of the Inspect tab described by @prettyv above .
Then one can import the previous export again which doesn't contain the Twitter links anymore (so don't play with the clear commands without an export/backup!).

See also https://github.com/kickscondor/fraidycat/wiki/Spelunking-Fraidycat's-Save-Files

I did disable and uninstall/reinstall the extension a few times so i'm not sure what the exact steps are to have the clean state (and I used the web extension of Firefox).

There are a few issues on starting over with a clean state, e.g. #78 

Fraidycat's storage handling is here: https://github.com/kickscondor/fraidycat/blob/master/src/js/storage.js

**Comment by solarchemist** [comment]
Have had the same problem. Thanks everyone for noting this issue. 
Of course it was caused by Twitter moving the goalposts again... 

Note that [any Nitter instance](https://github.com/zedeus/nitter/wiki/Instances) works as a replacement, not just `nitter.net`.

**Comment by kickscondor** [comment]
Really appreciate everyone's investigations - I am close on this, the data I am getting back from Twitter now is just drastically different. I have everything working though - except for threads.

**Comment by makew0rld** [comment]
Just tested a Twitter account for the first time in a long while, it appears to be working! Thank you @kickscondor!

**Comment by makew0rld** [comment]
Now that some time has passed... Twitter feeds don't seem to be updating. They were up-to-date when I first added them, but they are not changing from that point. @kickscondor would appreciate if this could be reopened.

**Comment by hoopyeah** [comment]
> Now that some time has passed... Twitter feeds don't seem to be updating. They were up-to-date when I first added them, but they are not changing from that point. @kickscondor would appreciate if this could be reopened.

You might want to open a new ticket. From my perspective, this one is (and has been) fixed. Both Twitter and Nitter follows stay up to date. I use:

- OS: Windows 10
- Browser: Firefox
- Version: Nightly

**Comment by makew0rld** [comment]
Hmm, thanks. Most feeds are back to working once again. One still has old data, and when I add it again, it says `e is undefined` as the error.  https://twitter.com/shaun_vids

**Comment by omentic** [comment]
There is a known issue where all feeds fail to update that can be reliably fixed by disabling and renenabling the extension. I wonder if you hit that.

**Comment by makew0rld** [comment]
Doing that didn't seem to work, unless there's more to it then just clicking disable and then enable.

**Comment by makew0rld** [comment]
And now https://twitter.com/shaun_vids is working again... not sure what's causing this change. I'll stop updating in this thread though, and open a new issue if needed.
