### ISSUE TITLE
"Add a follow" fails for some sites

### ISSUE THREAD

**Issue by johanbove** [kickscondor/fraidycat#24]
Console is showing "Error: i.fetch is not a function" in background.js
The "Save" button stays disabled.

URLS which are failing:
- https://indieweb.xyz
- https://seblog.nl

Screenshot:
![image](https://user-images.githubusercontent.com/922765/69460477-94151b00-0d74-11ea-9965-ba7887097aca.png)

No user message is presented.

**Comment by kickscondor** [comment]
Ok, thank you - there are similar problems if a site's DNS is down.

**Comment by kickscondor** [comment]
Ok I determined that the problem with seblog.nl. It was a typo bug for sites with only one feed.

**Comment by johanbove** [comment]
Thank you! 🖖
