### ISSUE TITLE
Fraidycat not updating feeds?

### ISSUE THREAD

**Issue by frioux** [kickscondor/fraidycat#248]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 102.0

**Describe the bug**

None of my feeds have updated for over a week.  At first I thought one of the feeds just had broken RSS, but now I can see that it's *all* of them not updating.  Content is in fact being published.  Example: https://thisisnthappiness.com/

![image](https://user-images.githubusercontent.com/8163/180613845-b4ea52d2-f1d8-4a97-9f9b-f56a2b3c0a4a.png)

**Comment by frioux** [comment]
I disabled and enabled the plugin and that seemed to unwedge it

**Comment by kickscondor** [comment]
Hey @frioux - yes, this issue is described elsewhere here. There is some bug that is causing the application to stop fetching. I appreciate you coming here to report this problem tho! Hopefully I can get a lead on what is tripping it up. Let me know how it goes.
