### ISSUE TITLE
"Update Frequency" tab indicator ignores "top" subreddit feeds. (Potentially intended?)

### ISSUE THREAD

**Issue by joshuacwnewton** [kickscondor/fraidycat#25]
Preface: I actually like this "buggy" functionality. I find it helpful that subreddits _aren't_ included! Just making this issue to check if it was intended or not.

-----

Link to feed: https://www.reddit.com/r/magicTCG/top/?sort=top

This subreddit feed (I think) always has a "green" indicator because it generally will get new "top" posts daily. But, the tab it's in won't be coloured green. See screenshots below:

![tab-ui-bug1](https://user-images.githubusercontent.com/16181459/69559957-c767cd80-0f5f-11ea-9b56-6af4fd000885.png)
![tab-ui-bug2](https://user-images.githubusercontent.com/16181459/69559958-c767cd80-0f5f-11ea-9d16-5abf82e3f986.png)

-----

I like this functionality of ignoring sources that update daily when determining tab colour. If you know the the source is always going to have green colouring, then there's no way to get useful information from the tab, because the tab will always be green too. But, if daily-update sources are ignored, then you can still get information on whether the less frequent sources have updated. (Like I'm getting with this "mtg" tag here.)

-----

Interestingly, I tried moving some other "daily" updating sources into Daily frequency and it also allowed them to be excluded from the tab coloring. I like this too!

-----

How much of this was intended, or is any of it unintended?

**Comment by kickscondor** [comment]
Haven't had a chance to look at this bug yet - but I agree with what you're saying. Those 'noisy' follows tend to stay at the top of the list and throw off the indicator. However, I don't want to mess with 'weights' or anything to alter them in the chronology - that's starting to venture into algorithm territory. Not sure yet what to do.

> Interestingly, I tried moving some other "daily" updating sources into Daily frequency and it also allowed them to be excluded from the tab coloring. I like this too!

This is intended - only 'real-time' follows should change the indicator. So yes, this is what I do with subreddits and overly active Twitter accounts that I still like to check on somewhat frequently - throw them in 'daily'.

Also, I'm a fan of Kenji as well. Helloooo friend.

**Comment by kickscondor** [comment]
Also experiencing this with Tumblr feeds...
