### ISSUE TITLE
Support using fraidycat without dependency on fraidyc.at domain (make it usable if fraidyc.at timeouts / 522 CloudFlare errors)

### ISSUE THREAD

**Issue by ronjouch** [kickscondor/fraidycat#258]
**EDIT** looks like fraidyc.at is back online. Awesome, but I remain interested in the possibility of using fraidycat through a fully-local browser-internal URL and fully-local resources (see "By the way" last 2 paragraphs of this issue).

**Before you start.**
* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop**
 - OS: Linux & Windows
 - Browser: Firefox 112.0b2 / 113.0 nightly
 - Version: 1.1.10
 - ~URL you are attempting to follow~ N/A

**Describe the bug**
Since 2023-03-15, the extension is unusable because https://fraidyc.at/ (or https://fraidyc.at/s/ ) fully fails to load, with a CloudFlare `Connection timed out` 522 error.

- I've been successfully using Fraidycat everyday for months/years. This hopefully isn't a "my browser is misconfigured" issue
- 100% reproducible on 2 machines.

<details>
  <summary>Screenshot of CF error page (click to expand)</summary>

![screenshot_fraidycat-522_2023-03-15-05:42:45](https://user-images.githubusercontent.com/522085/225270923-dfe14200-7b3d-4f1e-81e6-09aa2b172b7f.png)
</details>

Thanks for fraidycat :heart: .

---

By the way, is there a way to access the extension fully locally? Is there an "ugly browser-internal URL" (`moz-extension://<addonId>/` in Firefox) path to Fraidycat that doesn't depend on an external website to be up? Or am I wrong to assume the extension bundles its HTML/JS/CSS resources, and yes the website is actually necessary?

**Rationale**: It's sad / unexpected / weird to be unable to use a supposedly-local RSS reader when an arbitrary website is down. I was assuming that the extension opening at fraidyc.at/s was solely a cosmetic trick to avoid the ugly browser-internal URL, I didn't expect the extension to actually break if fraidyc.at is down 😕.

**Comment by ronjouch** [comment]
Looks like fraidyc.at is back online 🙂.

Awesome, but I remain interested in the possibility of using fraidycat through a fully-local browser-internal URL and fully-local resources (see "By the way" last 2 paragraphs of this issue). I renamed the issue to reflect this.

**Comment by igorlogius** [comment]
Been using fraidycat also for a while. And i was a bit shocked. 

I just took a look into the extension and it seems there is no internal page.

AFAICS, it really uses the external https://fraidyc.at/s  ... and injects some web_accessable resources. 

I guess this is/was the only way to get/show a "nice" url ... but i think security minded people might like to get the option to not rely on any external resources besides the ones that have been configured as feed endpoints. 

But maybe there is another reason i am simply not seeing right now. 

Hope we can get some feedback on this.

**Comment by rgieseke** [comment]
See also discussion and background for domain usage in https://github.com/kickscondor/fraidycat/issues/210

**Comment by ronjouch** [comment]
> See also discussion and background for domain usage in #210

@rgieseke a-ha, good find. That makes sense, I understand the reasons, the issue is clearly labeled as `help wanted`, there are a few paths forward to research, and new/improved WebExtension APIs might enable something better now (as opposed to 2 years ago).

→ I have nothing to add here. Will chime in #210 if I find something worth exploring, and closing this issue as dup.
