### ISSUE TITLE
https://fraidyc.at/ is down

### ISSUE THREAD

**Issue by hendersonreed** [kickscondor/fraidycat#260]
**Before you start.**
* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Linux, Android
 - Browser: Chromium, Firefox

**Describe the bug**
The general fraidycat server seems to be down - the root url of `https://fraidyc.at/` fails to load at all - this is true across browsers and devices. Hope it's coming back sometime! I'd like to get my feeds out of it at least (presumably those are stored locally and I can export them by digging around in the filesystem?)

**Comment by JoshMock** [comment]
We're already discussing on https://github.com/kickscondor/fraidycat/issues/210. Looks like the domain expired recently and is in the process of being deleted.

**Comment by randomprey** [comment]
I hope this service lives on somehow. <3

**Comment by poacher2k** [comment]
It's up again!! 🎉🎉🎉

**Comment by hendersonreed** [comment]
yep! it's back :heart: gonna close this issue, please see #210 regarding the cause of the issue and discussion on a potential fix down the line.
