### ISSUE TITLE
All Fraidycat feeds are out of date

### ISSUE THREAD

**Issue by lost-books** [kickscondor/fraidycat#261]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: [Linux, Windows, Mac] ventura 13.2
 - Browser [Chrome, Firefox, Onion, Vivaldi] firefox 
 - Version [e.g. 22] 112.0
 - URL you are attempting to follow [if applicable]

**Describe the bug**

when i load fraidycat, all my follows in every tab show a minimum age of 4 days, even when they have published multiple times since then, including within the past couple hours. 

everything was more or less working prior to the site going down a few days ago - tho i did occasionally see this issue that some follows were not up to date, but never carefully tracked it. now its everything across the board. 

thanks for taking a look.

**Comment by hendersonreed** [comment]
I have had the same experience - in the past I have occasionally seen this problem with a few follows here and there, but now nothing seems to be updating unfortunately.

**Comment by lost-books** [comment]
just wondering if there's anything i can do on my end for a fix here (e.g., self-hosting etc)

this has become easily one of my favorite apps & sad to not be able to have things up to date

thanks!

**Comment by lost-books** [comment]
issue appears resolve to me, closing. thanks!

**Comment by hendersonreed** [comment]
Unfortunately not resolved for me at this time, but hopefully there's work being done behind the scenes, or perhaps it will resolve itself over the coming days :/

edit: fixed!
