### ISSUE TITLE
NetworkError when attempting to fetch resource for every RSS feed. My feed hasn't updated in a couple days. 

### ISSUE THREAD

**Issue by fromthebunkers** [kickscondor/fraidycat#273]
**Before you start.**

* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Version 22H2
 - Browser: Firefox
 - Version: fraidycat version 1.1.10 for the Firefox browser.
 - URL: you are attempting to follow: any and all

**Describe the bug**
My fraidycat feed has not updated in a couple days. When I try to add a new URL it returns a NetworkError when attempting to fetch resource. Same with trying to edit my existing ones. The closest pre-existing file in the issuetracker was about Firefox Strict Tracking, so I made fraidycat an exception to that in my privacy settings. Hasn't changed anything. I switched to the standard level of Firefox Browser Privacy and tried again, didn't change anything.

**Comment by fromthebunkers** [comment]
Its started updating again, and I'm no longer getting network errors. However at least one of my subscribed URLs has lost its tags and been moved to the general feed, I haven't combed through my other tags to see if anything else has moved. That's not a major inconvenience but I think worth pointing out that something's causing that tag information to get wiped.

**Comment by nic-hartley** [comment]
Same bug, but it didn't fix itself, and I had to delete and reinstall the extension to get it to update (merely exporting/reimporting didn't work).  I'd attach logs but I can't find them anywhere.

**Comment by Kirby-Macintosh** [comment]
I have this bug too. It's been like this for a couple days and hasn't resolved itself. I'm using Fraidycat 1.1.7 for Mac OS X and my computer's OS version is 14.6.1

**Comment by tynehorne** [comment]
Same here — since 3 days ago, my existing feeds aren’t updating, and trying to add a new feed brings up the error from the original issue. I’m using version 1.1.10 on Firefox 132.0.1.

**Comment by fromthebunkers** [comment]
Its started happening to me again as well! Started two days ago, no self correction this time.

**Comment by noatpad** [comment]
Can also confirm this is happening to me! Don't know when it started exactly, but it was probably at the latest yesterday. Feeds haven't been updating, and I am unable to add new ones without that error popping up.
Running Firefox 133.0.3 (via the Zen Browser) with fraidycat 1.1.10 on Windows 10 22H2

**Comment by gamer4maker** [comment]
I also started having this problem a few days ago using Fraidycat 1.1.10 on Vivaldi 5.2.2623.4

**Comment by kickscondor** [comment]
I'm very sorry everyone. I've been doing some work on all of this and I screwed up. Give it another shot. :people_hugging:

**Comment by Kirby-Macintosh** [comment]
Works for me now. Thanks for the fix!

**Comment by fromthebunkers** [comment]
Working just fine for me too now!

**Comment by noatpad** [comment]
Working now! Thank you very much for the quick fix!

**Comment by kickscondor** [comment]
Thank you for reporting back everyone - closing.
