### ISSUE TITLE
Some feeds stall on the "Add a Follow" page when trying to add them.

### ISSUE THREAD

**Issue by joshuacwnewton** [kickscondor/fraidycat#33]
If I try to add this feed: https://www.stereogum.com/feed the Add Follow page hangs, as below.

![hanging-feed-add](https://user-images.githubusercontent.com/16181459/70931859-3f6c6500-1fed-11ea-8cd3-fb5043dd46f2.png)

I've had this happen a few times with other links, usually when I paste a website as-is (without trying to find its feed.) This is the first actual feed I can confirm it happens on.

**Comment by joshuacwnewton** [comment]
Update: This seems to be happening on feeds that previously worked, too. e.g. Tumblr blogs that I was able to add before.

**Comment by kickscondor** [comment]
Ok interesting. I recently pushed some fixes that should fix the stalling - I have no problem adding the Stereogum feed now (in Chrome.) What browser/OS are you in?

Can you also go to your 'add-ons' page and ensure that you are running Fraidycat 1.0.5? (I should probably add the version number to the settings page to make this more obvious.) Thank you for all your help Joshua.

**Comment by joshuacwnewton** [comment]
Good call! I was on 1.0.4 using Firefox 71.0. Updating to 1.0.5 fixes the problem. 

Thanks for the help! :)
