### ISSUE TITLE
Feature Request: Better Importance ordering

### ISSUE THREAD

**Issue by Yam76** [kickscondor/fraidycat#42]
Currently, when opening up a tag, there are several tabs that sort feeds based on importance. But this is a little strange, since I just want Importance to tell me how often a feed updates, and having to remember whether I've already checked my "Weekly" Importance this week is a pain.

My suggestion: Put the feeds under Importance headers, which are stacked up on top of each other under the tags. Like this:
```
TAG
Real-Time:
Feed1
Content/Content/Content
Feed2
Content/Content/Content
...
Weekly:
Feed3
Content/Content/Content
Feed4
Content/Content/Content
```
Only Importance levels which I've actually assigned should be shown.

When I am done reading the content under some level of Importance, let me mark that Importance level as "Done", which will hide it (maybe at the bottom?) for some amount of time.

For example, let's say I finish reading everything under "Weekly". I mark this as done, and the Weekly header is collapsed and pushed all the way to the bottom of the screen (out of sight, out of mind). If I check on the tag again in a day, I see no Weekly, because I've already marked it as Done. But come next week, Weekly is back on my feed. Marking Weekly as Done forced all the media within Weekly to wait until next week to show themselves again.

This gives users control over which media is thrown into their face by using a time limit to constrict the flow of media.

**Comment by kickscondor** [comment]
Hehe oh no - I actually had it this way originally (with everything under a tag on one page) but everyone who used it complained about it. 😂 So I've moved to keeping importance under separate pages and, after extended use, I think it's better. The older importances should be out of the way so they don't distract you. And, no, there's no timer helping you check weekly - it's up to you to regulate yourself and decide what these 'importances' mean to you. I really don't want Fraidycat driving you.

Marking things as 'read' or 'done' is not something I plan to bring to Fraidycat. I know this is a huge departure from other RSS readers - but if you are using it to track hundreds (hopefully thousands, eventually) of websites, there's just no possible way to manage the landslide of 'unread' messages.

You just drop into Fraidycat and read whatever you feel like reading. That's the whole vibe. No notifications, no 'you have X unread messages.' (I'm sorry!)

Thank you for checking out Fraidycat! I appreciate you taking the time to write out your thoughts. I am not beyond changing my mind, but it will take time.

**Comment by Yam76** [comment]
That's pretty fair. I guess in my mind, the cognitive overhead of having to remember whether I already checked my feeds each week is annoying enough to offload onto the program itself, but I can definitely see how that could create an "unread messages" effect, especially as the number of feeds tracked increases. Thank you for your reply.
