### ISSUE TITLE
Make tagging 🏠 easier

### ISSUE THREAD

**Issue by jmacdotorg** [kickscondor/fraidycat#44]
I like Fraidycat's philosophy that everything must have at least one tag, and making "🏠" the default if the user doesn't specify anything.

However, I find that when I'm adding categorized feeds, I quite often want them to be 🏠 plus something else: let that feed show up in my main view, and also in this tag-filtered view. I don't mind reaching into the emoji drawer to find the right something-else, but having to hunt for that house icon *every time* seems suboptimal.

Consider, perhaps, an "Also add to 🏠" checkbox, or having a little palette of click-to-add emoji tags with 🏠 always present, or something...

**Comment by kickscondor** [comment]
Ah ok - interesting thought! I don't do much multiple tagging, so I'm interested to hear how people use this. I could have the home emoji be present unless you delete it... Let me think on this. Thank you for taking the time to offer all of these suggestions!

**Comment by jmacdotorg** [comment]
Honestly the choice of that default emoji guided me... it doesn't suggest "uncategorized", (which was maybe your intent?) but "home", and it makes sense to me that almost everything should "live" there...

**Comment by kickscondor** [comment]
Ok, I think I've sorted out a fix for this. Trying to push this out soon. The home icon now shows up as the default tag. This actually dovetails right into #34.
