### ISSUE TITLE
Network error when trying to fetch resource.

### ISSUE THREAD

**Issue by 7415963987456321** [kickscondor/fraidycat#45]
Hello, I just installed Fraidycat on Firefox 71.0,
but I get 'Network error when trying to fetch resource.' every time I try to add something to the feed.

Any idea what could be going wrong?

**Comment by kickscondor** [comment]
I'm also getting an issue on a certain Chromebook - can't seem to fetch Twitter follows.

I haven't seen this on Firefox before. What operating system? Also - do you have strict tracking protection on?

**Comment by 7415963987456321** [comment]
@kickscondor Running linux. 
After disabling strict tracking protection everything works as intended. Currently trying to find out whether or not the tracking protection thingamajig has a whitelist somewhere.

**Comment by kickscondor** [comment]
Ok thank you - we'll continue this research in #26.
