### ISSUE TITLE
Firefox extension doesn't retain feeds

### ISSUE THREAD

**Issue by clmbmb** [kickscondor/fraidycat#46]
OS: Fedora 31 64bit
Kernel: 5.3.15-300.fc31.x86_64
Firefox: 71.0 (64-bit)
Firefox account: logged in

I open the Fraidycat tab/window, add a few RSS feeds, which show up perfectly, then get on with my stuff. When I want to open the tab again, it's empty: no RSS feeds saved.

**Comment by kickscondor** [comment]
Hmmm, very strange. I did quite a bit of testing on Firefox for Ubuntu last night - not sure about Fedora. Check the add-ons page. Are you on version 1.0.6? There were a lot of changes to saving and syncing in that version.

Thank you for reporting this!

**Comment by kickscondor** [comment]
After a lot of testing on Linux, Windows and Mac, I actually have the opposite problem now - feeds really stick around, even if you log out. But please reopen if there is a problem after 1.1.0 comes out.
