### ISSUE TITLE
Mac Stand-alone Fraidycat does not quit without force

### ISSUE THREAD

**Issue by jmacdotorg** [kickscondor/fraidycat#47]
macOS 10.14.6, standalone version:

The Quit command closes the Fraidycat window, but the app continues to run. It exits only if you force-quit it.

**Comment by kickscondor** [comment]
Yes, this is fixed in 1.0.6 which is coming out tomorrow.

**Comment by kickscondor** [comment]
Actually, you can also quit now using the Fraidycat icon in the menu bar.

The code for this change is already checked-in. And I will likely be removing the menu bar icon - I'm not a Mac user, but I imagine this is less useful on Mac than on Windows and Linux.
