### ISSUE TITLE
Strip hash anchors at the end of TiddlyWiki (and other) URLs.

### ISSUE THREAD

**Issue by TiddlyTweeter** [kickscondor/fraidycat#48]
Since you like TiddlyWiki I thought to comment that on feed "[TiddlyWiki Pre-release](https://tiddlywiki.com/prerelease/)" some addresses don't resolve though shown ... Its likely a TW issue? Not Le Cat? Other TW deliver the baby. Prerelease is often a 404.

**Comment by kickscondor** [comment]
Not sure what you mean. I can pull it up fine.
![2019-12-18 12 26 51 hecfkgekabkkhiidlinmifelhdooeool 05802c7e25af](https://user-images.githubusercontent.com/12375777/71116675-cbb78d00-2191-11ea-9a49-46b69ef9126c.png)
And the links work. Can you give me some specifics?

**Comment by TiddlyTweeter** [comment]
Right. Its some kind of obscure issue. I get on chrome 404 on all the sub addresses on pre-release. Even after hard refresh. Doubt its your issue. Let see if I can pin it down.

**Comment by TiddlyTweeter** [comment]
I deleted the feed and re-did it. NOW it works. So I closed it. Hopefully it is done.

**Comment by kickscondor** [comment]
It occurs to me that perhaps the URL had the '#' anchor in it. This didn't cause 404s - but it did cause problems. I should strip those in the case of a TiddlyWiki.
