### ISSUE TITLE
Can't seem to add Slashdot, even though it has RSS

### ISSUE THREAD

**Issue by scott-wi** [kickscondor/fraidycat#49]
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 71

Cannot seem to add Slashdot.org to feeds, either by adding via homepage or by pointing directly to the RSS feed. 

Attempted:
https://slashdot.org
http://rss.slashdot.org/Slashdot/slashdotMains

**Comment by kickscondor** [comment]
Yes - ok this is an issue with Feedburner feeds. It's returning HTML to me instead of RSS. I need to send an Accept header in this case. Noted.

**Comment by kickscondor** [comment]
Ok, there are also issues with the feed itself. Some work to do here.

**Comment by scott-wi** [comment]
Thanks for taking a look at this - you rock man.

**Comment by kickscondor** [comment]
This is fixed - should be out Monday. Thank you for your patience.
