### ISSUE TITLE
Move expand/collapse button to the left side

### ISSUE THREAD

**Issue by scott-wi** [kickscondor/fraidycat#50]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
If you're running the app full screen, it's a long drag to the right to reach the expand button, and then to close, it moves all the way back to the left. Would be nice if it was always on the left, perhaps just under the feed title, inside of the indent.

**Comment by kickscondor** [comment]
Ok, cool - I dig. I'll need to think about the look of this - because I don't want the left-side to become too visually cluttered.

But yeah - thank you for the great idea.

**Comment by kickscondor** [comment]
I think I finally have an answer for this, but it's going to have to wait until I do further work on the layout. Just don't want to change it twice and confuse everyone. Apologies for the delays on this.

**Comment by kickscondor** [comment]
This change has been made. Will be out today.
