### ISSUE TITLE
arXiv feeds not working

### ISSUE THREAD

**Issue by adeel** [kickscondor/fraidycat#60]
**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Electron app
 - Version 1.0.7

**Describe the bug**
There seems to be an issue with adding [arXiv feeds](https://arxiv.org/help/rss), such as [arXiv/math.AG](https://arxiv.org/rss/math.AG): I get a "No Feeds Discovered" error.

**Comment by kickscondor** [comment]
This appears to be related to #49. This is an RDF-style RSS feed, which isn't supported by the library I'm using for RSS. I plan to replace this library by late February, so keep an eye out.

And hey - thank you for reporting this.

**Comment by adeel** [comment]
Great, thank you so much.

**Comment by kickscondor** [comment]
This is now addressed with the merge of 1717d62 which supports RDF and items without a timestamp. Release should be on Monday.
