### ISSUE TITLE
Show more information about feeds before adding

### ISSUE THREAD

**Issue by robertbrook** [kickscondor/fraidycat#61]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**

When subscribing to an RSS feed and multiple feeds are found, it would be very useful to show the URL of each candidate feed. 

This would provide more hints to users to allow them to choose which feed to add.

**Comment by kickscondor** [comment]
Sweet - great idea! Thanks.

**Comment by kickscondor** [comment]
This is introduced in the e08f800 changes. Should be out Monday.
