### ISSUE TITLE
Unable to import inoreader OPML export - silently doesn't add any follows

### ISSUE THREAD

**Issue by offbyone** [kickscondor/fraidycat#75]
**Desktop (please complete the following information):**
 - OS: [Linux, Windows, Mac] **Mac**
 - Browser [Chrome, Firefox, Onion, Vivaldi] **Chrome**
 - Version [e.g. 22] **80.0.3987.116**

**Describe the bug**

I exported my subscriptions from [inoreader](inoreader.com) as OMPL. It's a list of RSS feeds, mostly. I then tried Fraidycat's OPML import button, and ... nothing. I don't see any logs in the site console and no feeds seem to have been imported.

**Comment by offbyone** [comment]
If there are reduced examples you'd find helpful, let me know. I'll get what I can.

**Comment by kickscondor** [comment]
No, I think I'm ok for now. Thank you for reporting this. I'll get back to you if I need more, but I've verified that this is the case. I should have this out by the end of the week.

**Comment by kickscondor** [comment]
This is fixed in my testing. Reopen after 1.1.2 if it's still an issue for you.

**Comment by Abogeniero** [comment]
Is the function "Export OPML" now PRO? I have the lateast version and I'm trying to crate the OPML file but I can't find the "Export" option

**Comment by kickscondor** [comment]
@Abogeniero no - if you have the extension, it should be in the 'settings' area.

![2022-06-29 12 28 27 fraidyc at 6ac67b94aed3](https://user-images.githubusercontent.com/12375777/176509679-449d6a40-5f35-4a66-bdb0-cf527a60f5fe.png)

If you are building from the main branch, then it just hasn't been added yet.
