### ISSUE TITLE
Unable to use a slash in tags

### ISSUE THREAD

**Issue by 2hsieh** [kickscondor/fraidycat#77]
If I use `/` in the name of a tag, the tag will just return to the home tag when clicked. For instance, if I name a tag film/tv, clicking on film/tv just brings me to the home tag, instead of the list of items I've tagged as film/tv.

This makes it impossible to access the feeds that I've tagged as film/tv, as attempting to re-add the RSS feeds returns a "this is already in your subscriptions" error.

![image](https://user-images.githubusercontent.com/9558242/75405147-9d58db00-58c1-11ea-9b4c-0104680e81b9.png)

In the above, I have clicked on film/tv and the browser returns this page. The URL then is `chrome-extension://hecfkgekabkkhiidlinmifelhdooeool/index.html#!/tag/film/tv`.

**Comment by kickscondor** [comment]
Ok - great. Good point - I'll get this worked out. In the future, I may turn these into subtags - I'll have to think about how to fit that into the design.

Thank you, Andrew.

**Comment by kickscondor** [comment]
Fixed by a055da2.
