### ISSUE TITLE
Hot to clear Fraidicat data on Firefox?

### ISSUE THREAD

**Issue by fmanclossi** [kickscondor/fraidycat#78]
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 73.0.1

I've imported too much items in Fraidicat and I want to clean up and reinstall the addon.
I remove it from Firefox Addon panel and I reinstalled it... but the data are still there.
How can I clean up Fraidicat data?

Thanks in advance, interesting app

**Comment by kickscondor** [comment]
Hi, Ferruccio! Yes - I need to make this happen for my own purposes as well.

This is actually a duplicate - we've been discussing this in #71. I've bumped up the importance though, in the hopes of adding this by Monday.

**Comment by taobojlen** [comment]
I don't see any discussion of this in #71 (nor elsewhere in this repo) -- I might be missing something, but should this issue maybe be reopened?
