### ISSUE TITLE
Permanent blank window on macOS

### ISSUE THREAD

**Issue by jmacdotorg** [kickscondor/fraidycat#79]
**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Standalone
 - Version: 1.1.0

**Describe the bug**
The standalone app shows only a blank white window (see screenshot). This persists across a full system reboot.

This behavior began after a handful of normal-usage launches of the application.

Would be happy to help debug; am not sure where to find diagnostic information et al.

<img width="867" alt="Screen Shot 2020-03-02 at 10 50 34 AM" src="https://user-images.githubusercontent.com/621995/75692963-53cb1000-5c74-11ea-832a-d0d2cdcb6172.png">

**Comment by kickscondor** [comment]
This is similar to #71. What is likely going on is that you have a follow that is triggering some exception that's not being captured in the template.
 
I discuss debugging this [here](https://github.com/kickscondor/fraidycat/issues/71#issuecomment-590921499). However, you'll need a debug build for Mac - it'll give you a menu item to open the debugging tools.

A simpler way to debug this would be to zip up your Fraidycat directory and send it to me - if you don't mind doing that. (Of course I understand if you do mind doing that!) Even just giving me your follows.json from that directory should do it. (The directory is in your personal Library folder, Application Support, Fraidycat.)

Thank you for reporting this! There has been a lot of bug-fixing to do after the cataclysmic changes of 1.1 and I appreciate your not giving up when the blank window started to appear.

**Comment by jmacdotorg** [comment]
Mailed you my follows.json. Thanks!

How does one make a debug build? (naively searched for "debug" in the readme and came up empty)

**Comment by kickscondor** [comment]
Okay, solved the blank page problem. Also solved a problem with missing URLs in the follows index. Still working on an issue with some updates not hitting the main page.

Thank you for passing the files over - this has been a trove.
