### ISSUE TITLE
Image files are broken.

### ISSUE THREAD

**Issue by 7415963987456321** [kickscondor/fraidycat#85]
**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Firefox]
 - Version [e.g. 73.0.1]

**Describe the bug**
The png images in /src/images do not work at all on firefox, not on the page and not when I load them directly.  I ran the files through the pngchecker utility and it reports that it can neither read it as a PNG or a JPEG. I cannot even display them with imv or gimp. 

Actually realizing just now that they are just ASCII files that point to the Github large file storage..... Is this just some weird github error?

**Comment by kickscondor** [comment]
Are you building from source or something? If so, you need to install git-lfs.

**Comment by 7415963987456321** [comment]
Yes I am building from source.

>  If so, you need to install git-lfs.

Ah I see that now... didn't have git lfs installed, maybe it should be mentioned in the build instructions. Although I am struggling with getting lfs to get the actual images. I'll probably figure it out.

**Comment by kickscondor** [comment]
I believe you need to install git-lfs before you clone the repository. Thank you for pointing this out - I had forgotten this step.
