### ISSUE TITLE
Dark mode is always on

### ISSUE THREAD

**Issue by Hechss** [kickscondor/fraidycat#87]
**Desktop**
 - OS: [Windows]
 - Browser [Edge Chromium]
 - Version [80]

**Describe the bug**
Background is always dark. Ticking / unticking the "Dark mode" option doesn't change anything.

**Comment by kickscondor** [comment]
Do you have "dark mode" on in the operating system? Because Fraidycat will default to dark mode in that situation.

**Comment by Hechss** [comment]
Yes I have! That's the reason then! 

Since it exists a switch for "light mode" users who want to see a dark Fraidycat, it doesn't make much sense that "dark mode" users can't change it too.
I guess it would be better to change it to a **Light/Dark/As my OS**  option. Just take it into account in the future. Congrats for your tool!!

**Comment by p2kmgcl** [comment]
@kickscondor can I contribute with a pull for this?

**Comment by kickscondor** [comment]
> @kickscondor can I contribute with a pull for this?

That'd be dope. Thanks!

**Comment by kickscondor** [comment]
And actually: the way I'd like to do it is to have the "Dark Mode" option change to "Light Mode" when dark mode is on at the OS level.
