### ISSUE TITLE
HackerNews Comments / Parsing of description

### ISSUE THREAD

**Issue by JasonSwindle** [kickscondor/fraidycat#93]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
HackerNews in the descriptions area has comments, and I would to have the link back to these.  

### RSS
``` xml
        <item>
            <title>A Peek Into Graviton2</title>
            <link>https://www.anandtech.com/show/15578/a-peek-into-the-physics-of-graivton2-amazons-neoverse-n1-server-chip-first-impressions</link>
            <pubDate>Tue, 10 Mar 2020 15:56:40 +0000</pubDate>
            <comments>https://news.ycombinator.com/item?id=22536539</comments>
            <description><![CDATA[<a href="https://news.ycombinator.com/item?id=22536539">Comments</a>]]></description>
        </item>
```

**Comment by kickscondor** [comment]
Yes - good idea. This will have to be part of the upcoming 1.2.0 redesign.

**Comment by kickscondor** [comment]
Watch #30 - it covers this. I'm sorry about the delay - I keep messing with the design of it.
