### ISSUE TITLE
Cannot add public Instagram profiles: NetworkError

### ISSUE THREAD

**Issue by frafra** [kickscondor/fraidycat#96]
**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 1.1.2
I am using the browser extension.

**Describe the bug**
Cannot add Instagram public profiles, such as: https://www.instagram.com/dario.bressanini/
Error message: `NetworkError when attempting to fetch resource.`

**Comment by nkoehring** [comment]
Same here. Looks like the same problem.

* Linux
* Firefox
* Browser extension via Mozilla "store"

**Comment by semalPatel** [comment]
I tried adding a subreddit. Same problem
* MacOS
* Firefox extension

**Comment by mmccollow** [comment]
I have the same issue trying to add a person's Twitter profile. Firefox 73 on Fedora Linux 30, Fraidycat 1.1.2 installed via addons.mozilla.org.

**Comment by kickscondor** [comment]
Yes - this is likely a conflict with Firefox's "Strict" Tracking Protection. (See #26.) I'm not sure yet how to work around this. It thinks that accessing twitter.com or instagram.com from the extension is "calling home". And I can understand why!

**Comment by quad** [comment]
[According to MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#Host_permissions), this issue can be solved by explicitly adding `twitter.com`, `instagram.com`, and other sites to the `manifest.json`.
