### ISSUE TITLE
Save button disabled when deletion is cancelled

### ISSUE THREAD

**Issue by benplumley** [kickscondor/fraidycat#97]
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 68.6.0esr
 - Fraidycat version: 1.1.2

**Describe the bug**
The `Save` and `Delete This` buttons on the Edit a Follow page stops working if the `Delete This` button is clicked and the `Cancel` button in the resulting "Delete x?" dialogue is clicked.

To reproduce:
1. Add a follow.
2. Go to the homepage then click the pencil icon to edit the follow.
3. Click the Delete This button.
4. Click Cancel.

**Comment by kickscondor** [comment]
Ah good catch! Thank you so much.
