### ISSUE TITLE
Add support for Youtube Playlists

### ISSUE THREAD

**Issue by benplumley** [kickscondor/fraidycat#98]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
We can follow Youtube channels, but some channels post multiple very different streams of content - Youtube allows the channel owner to sort these into playlists.

For instance, if I want to follow Critical Role on Youtube, I'd have to follow the Geek & Sundry channel, but the majority of the videos published by that channel have nothing to do with Critical Role. The feature I'd like to see is the ability to follow Playlist pages on Youtube, such as [this playlist of Critical Role episodes.](https://www.youtube.com/playlist?list=PL7atuZxmT955Cw-fFS-_3IQvaCpQgDzWA)

**Comment by kickscondor** [comment]
Awesome idea - thank you!
