### ISSUE TITLE
Create a "Fraidy Follow" bookmarklet

### ISSUE THREAD

**Issue by frandroid** [kickscondor/fraidycat#99]
**Before you start.**

* [X] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
Create a fraidy follow bookmarklet so when I want to follow a user, I don't need to copy the URL and then open up the Fraidy app and then paste it there manually, I can just click the bookmarklet and voilà, now I just need to confirm the frequency.

Optionally: Could be smart enough to follow someone from a user's single tweet's page rather than their twitter profile page, for example.

**Comment by kickscondor** [comment]
Cool - I like this! Wonder if I can get this working with the desktop app as well... Thank you for the detailed write-up.

**Comment by kickscondor** [comment]
Okay this is working with the latest version. The bookmarklet is:

    javascript:location.href='https://fraidyc.at/s#!/add?url='+
      encodeURIComponent(location.href)+'&title='+
      encodeURIComponent(document.title)
